# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160611_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['ordering'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
